---
output: html_notebook
---
<br />
<br />
<br />
***Q: How does landscape and habitat selection affect NOGO diet at the nest?***

### 1: Identify key foraging areas.
1. Measure breeding season home range size.
    1. Define "breeding season".
    2. Generate 95% and 50% KDEs for each bird.
    3. Measure KDEs.
2. Identify movement behvaiors (traveling, resting, and foraging) from telemetry data.
    ...using HMMs & `moveHMM` or similar.
3. Use foraging-only locations to identify foraging habitat.
    ...using KDEs again, or LoCoh...?

### 2: Quantify breeding season diet.
1. Create table of likely prey species.
    Include scientific name, common name, genus & family, m & f mean size, source.
2. Identify prey...
    1) from pellets & remains
    2) from nest cameras
    3) record timestamps of deliveries
4. Quantify richness and evenness of diet.

### 3: Model landscape and habitat selection as predictors of diet.
1. Compile landscape data.
2. Examine variation in diet across gradient of precipitation (coast/transition)
3. Model predictors of diet.
4. Trackback deliveries to kill sites.
5. Model kill sites as predictor of prey?

### 4. Write!
1. Write methods.
2. ...and everything else.