---
title: "Landscape variable selection, ctd"
output: html_notebook
---

As a control, and as further assessment of the models, use model output from HSI models by Mahon et al. Although a separate model exists for nesting and foraging habitat, both models should be used. Although goshawks are known to be more flexible in their requirements for foraging habitat than for nesting habitat (which is reflected in the simpler HSI-f), nesting-type habitat may represent preferred habitat for foraging as well.

To capture broad-scale patterns in habitat characteristics, use BEC subzones and variants. Although this will not reflect small-scale features goshawks may be selecting (or avoiding) such as water features or open space, it will reflect the general forest types available to goshawks and how that availability varies between sites and across the study area.

The HSI-f is a simple model which does not include a number of variables that may influence where goshawk forage, what they hunt, and how successfully they reproduce. To assess the potential impacts of different land covers, including both those known to benefit goshawks and those which may benefit them indirectly, consider 8 cover types:

1. Old-growth forest (decadent, multilayered)
2. Mature forest (large trees & open)
3. Young & regenerating forest (stand initiation, pole/sapling)
4. Hardwood forest (including riparian?)
5. Clearcut/cut block (may be different than other "open" covers)
6. Open (including meadows, alpine, scree/talus, wetlands, agriculture)
7. Urban
8. Water (rivers, lakes, and ocean)

## Wednesday meeting

* Maybe switch agriculture to urban category to capture human activity and exurban nature of urban development within NOGO habitat.

* Define age classes for old/mature/young.

* Work on selecting landscape metrics.