# This takes the raw .csv file generated by the base station
# and cleans it up for further analysis.

rm(list = ls())   # Clear the workspace.
gc()            # Perform a garbage collection.

setwd('C:/Users/Gwyn/sfuvault/Data/Telemetry')

# Load some libraries.
library('lubridate')
library('tidyr')

# Import raw data.
# Change the sep value as needed.
df <- read.csv(
  'MtCurrie/HAR09_CLEAN_2019-06-11_2019-07-02.csv',
  header = TRUE, sep = ',')

# Create a single column for time.
df$time <-
  strptime(paste(df$Year, df$Month, df$Day, df$Hour, df$Minute, df$Second), 
           format='%Y%m%d%H%M%S', tz='UTC')

# Convert timezone from UTC to PT
df$time <- with_tz(df$time, tzone = "America/Los_Angeles")

# Clean up empty columns.
e.cols <- c('Year', 'Month', 'Day', 'Hour', 'Minute', 'Second', 'Altitude', 
            'Div.up', 'Div.down', 'No.GPS...diving', 'Diving.duration', 
            'Raw.latitude', 'Raw.Longitude', 'Decision.voltage', 'Milisecond', 
            'Acc_X', 'Acc_Y', 'Acc_Z')

df <- df[ , !names(df) %in% e.cols]

df$X <- NULL

# Rename columns in consistenst, shorter way.
names(df) <- 
  c('id', 'lat', 'lon', 'speed', 's.time', 'volt', 'temp', 'no.fix', 
    'at.base', 'datetime')

names(df)[names(df) == 'fix'] <- 'no.fix'

# Fill in NAs
df$no.fix <- replace_na(df$no.fix, 0)
df$at.base <- replace_na(df$at.base, 0)

df$at.base <- 'NA'

## Save to csv file for further manipulation
write.csv(df, file='MtCurrie/HAR09_CLEAN_2019-06-11_2019-07-02.csv', 
          row.names=FALSE)
